//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUIT
    {
        public string ID { get; set; }
        public string DESIGNATION { get; set; }
        public Nullable<decimal> PUHT { get; set; }
    }
}
